import { cssr } from '../cssr'
import { styles as sharedStyles } from '../theme'

const { c, bem: { b, e, m } } = cssr
const { primary, dimmed, borderL2, brand, layer1, hover } = sharedStyles

/** 设置侧边栏：整窗 docked 左栏 + 内容区。 */
export default b('settings-sidebar', {
  '--dsh-chat-content-width': '748px',
  '--dsh-composer-card-max-width': 'calc(var(--dsh-chat-content-width) + 32px)',
  '--dsh-composer-side-clearance': '16px',
  'position': 'fixed',
  'inset': 0,
  'zIndex': 1000,
  'display': 'flex',
  'background': 'var(--dsw-alias-bg-base)',
  'color': primary,
}, [
  e('rail', {
    flex: 'none',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    width: 'var(--dsh-settings-rail-width)',
    padding: '6px 12px',
    background: 'var(--dsw-specific-sidebar-fill)',
    borderRight: '1px solid var(--dsw-alias-border-weak, rgba(127,127,127,0.2))',
    overflow: 'hidden',
  }),
  e('back', {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    alignSelf: 'flex-start',
    padding: '6px 10px',
    border: 'none',
    background: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    fontFamily: 'inherit',
    width: '100%',
    fontSize: '14px',
    lineHeight: '22px',
    color: primary,
  }, [
    c('&:hover', { background: hover }),
  ]),
  // 搜索框 = 官方 input 样式值（与 dsh-tauri-panel-scheduler 的 K.input 一致，
  // 复刻 ModelsSection.zGbnIq_input；令牌化，浅/深色自动适配）。
  e('search', {
    boxSizing: 'border-box',
    border: '.5px solid var(--dsw-alias-border-l4)',
    width: '100%',
    height: '32px',
    font: 'inherit',
    background: layer1,
    color: primary,
    borderRadius: '8px',
    padding: '0 10px',
    fontSize: '14px',
    lineHeight: '22px',
    outline: 'none',
  }, [
    c('&:focus', { borderColor: brand }),
    c('&::placeholder', { color: dimmed }),
    c('&:disabled', { opacity: '.6', cursor: 'default' }),
  ]),
  e('nav', {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    flex: 1,
    overflowY: 'auto',
    minHeight: 0,
  }),
  e('nav-item', {
    boxSizing: 'border-box',
    height: '40px',
    padding: '9px 12px',
    border: 'none',
    background: 'none',
    borderRadius: '12px',
    textAlign: 'left',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: '14px',
    lineHeight: '22px',
    fontWeight: 400,
    color: primary,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  }, [
    m('active', {
      background: 'var(--dsw-specific-sidebar-nav-item-active)',
      fontWeight: 500,
    }),
  ]),
  e('nav-label', {
    flex: 1,
    minWidth: 0,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }),
  e('empty', {
    padding: '12px 10px',
    fontSize: '13px',
    lineHeight: '20px',
    color: 'var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary))',
  }),
  e('handle', {
    flex: 'none',
    alignSelf: 'stretch',
    width: '8px',
    marginLeft: '-4px',
    zIndex: 2,
    cursor: 'col-resize',
    touchAction: 'none',
    background: 'transparent',
    borderRadius: '4px',
  }, [
    m('dragging', { background: borderL2 }),
  ]),
  e('content-outer', {
    flex: 1,
    minWidth: 0,
    height: '100%',
    boxSizing: 'border-box',
    overflowY: 'auto',
    display: 'flex',
  }),
  e('content-inner', {
    width: 'min(calc(var(--dsh-composer-card-max-width) + 2 * var(--dsh-composer-side-clearance)), 100%)',
    margin: '0 auto',
    boxSizing: 'border-box',
    padding: '28px 36px',
  }),
])
