//! shim 脚本内容生成：`dsh` / `pnpm` 的 cmd、ps1、sh 包装脚本构建函数。
//! 各构建函数是纯函数（便于测试），落盘见 [`super::write`]。
//! shim 文本必须全英文：cmd/ps1 按系统代码页解析，中文注释会乱码成命令执行。

use std::path::Path;

use super::escape_path_cmd;
use super::escape_path_ps1;
use super::escape_path_sh;
#[cfg(not(windows))]
use super::templates::SH_USER_DSH_PRECEDENCE;
use super::templates::{
    CMD_NODE_RESOLVE, CMD_USER_DSH_PRECEDENCE, PS1_NODE_RESOLVE, PS1_USER_DSH_PRECEDENCE,
    SH_NODE_RESOLVE,
};

// ---------------------------------------------------------------------------
// dsh shim
// ---------------------------------------------------------------------------

/// Windows `dsh.cmd` 内容。`app_dir` 为应用数据目录（绝对路径，生成时写死），
/// `dsh_home` 为官方 `$DSH_HOME`（release 为 `~/.dsh`，生成时写死，与桌面端/
/// 官方一致）。
#[cfg_attr(debug_assertions, allow(dead_code))] // 仅 release 构建写入 dsh shim
pub fn build_cmd_shim(app_dir: &Path, dsh_home: &Path) -> String {
    let dsh_bin = app_dir.join("dependencies/dsh/node_modules/@deepseek-ai/dsh/lib/bin.js");

    format!(
        r#"@echo off
rem DeepSeek Harness Desktop - dsh command shim (generated)
rem Do not edit: regenerated by the desktop app on install/startup.
setlocal
set "APP_DIR={app_dir}"
rem Use bundled MinGit only when system Git lacks its HTTPS transport helper.
set "SYSTEM_GIT_WORKS="
for /f "delims=" %%g in ('git --exec-path 2^>nul') do if exist "%%g\git-remote-https.exe" set "SYSTEM_GIT_WORKS=1"
if not defined SYSTEM_GIT_WORKS if exist "%APP_DIR%\dependencies\git\cmd\git.exe" set "PATH=%APP_DIR%\dependencies\git\cmd;%PATH%"
{user_dsh}
set "DSH_BIN={dsh_bin}"
set "DSH_HOME={dsh_home}"
set "DSH_TELEMETRY_DISABLED=1"
{node_resolve}
:launch
if not exist "%DSH_BIN%" goto :no_cli
"%NODE%" "%DSH_BIN%" %*
exit /b %ERRORLEVEL%

:no_cli
echo [dsh] Harness CLI not found. Please run DeepSeek Harness Desktop to install it first. 1>&2
exit /b 1

:no_node
echo [dsh] Node.js runtime not found. Please run DeepSeek Harness Desktop to install it first. 1>&2
exit /b 1
"#,
        app_dir = escape_path_cmd(app_dir),
        dsh_bin = escape_path_cmd(&dsh_bin),
        dsh_home = escape_path_cmd(&dsh_home),
        user_dsh = CMD_USER_DSH_PRECEDENCE,
        node_resolve = CMD_NODE_RESOLVE,
    )
}

/// Windows `dsh.ps1` 内容
#[cfg_attr(debug_assertions, allow(dead_code))] // 仅 release 构建写入 dsh shim
pub fn build_ps1_shim(app_dir: &Path, dsh_home: &Path) -> String {
    let dsh_bin = app_dir.join("dependencies/dsh/node_modules/@deepseek-ai/dsh/lib/bin.js");

    format!(
        r#"# DeepSeek Harness Desktop - dsh command shim (generated)
# Do not edit: regenerated by the desktop app on install/startup.
$ErrorActionPreference = "Stop"
$appDir = '{app_dir}'
$dshBin = '{dsh_bin}'
# Use bundled MinGit only when system Git lacks its HTTPS transport helper.
$systemGitWorks = $false
try {{
    $gitExecPath = & git --exec-path 2> $null
    $systemGitWorks = ($LASTEXITCODE -eq 0) -and (Test-Path -LiteralPath (Join-Path $gitExecPath 'git-remote-https.exe'))
}} catch {{}}
if (-not $systemGitWorks) {{
    $gitDir = Join-Path $appDir 'dependencies\git\cmd'
    if (Test-Path -LiteralPath (Join-Path $gitDir 'git.exe')) {{
        $env:PATH = $gitDir + ';' + $env:PATH
    }}
}}
{user_dsh}
$dshHome = '{dsh_home}'
$env:DSH_TELEMETRY_DISABLED = '1'
{node_resolve}
if (-not (Test-Path -LiteralPath $dshBin)) {{
    Write-Error '[dsh] Harness CLI not found. Please run DeepSeek Harness Desktop to install it first.'
    exit 1
}}
$env:DSH_HOME = $dshHome
& $node $dshBin @args
exit $LASTEXITCODE
"#,
        app_dir = escape_path_ps1(app_dir),
        dsh_bin = escape_path_ps1(&dsh_bin),
        user_dsh = PS1_USER_DSH_PRECEDENCE,
        node_resolve = PS1_NODE_RESOLVE,
        dsh_home = escape_path_ps1(&dsh_home),
    )
}

/// Unix `dsh` shell 脚本内容（POSIX sh）
#[cfg(not(windows))]
#[cfg_attr(debug_assertions, allow(dead_code))] // 仅 release 构建写入 dsh shim
pub fn build_sh_shim(app_dir: &Path, dsh_home: &Path) -> String {
    let dsh_bin = app_dir.join("dependencies/dsh/node_modules/@deepseek-ai/dsh/lib/bin.js");

    format!(
        r#"#!/bin/sh
# DeepSeek Harness Desktop - dsh command shim (generated)
# Do not edit: regenerated by the desktop app on install/startup.
APP_DIR='{app_dir}'
DSH_BIN='{dsh_bin}'
{user_dsh}
export DSH_HOME='{dsh_home}'
export DSH_TELEMETRY_DISABLED=1
{node_resolve}
if [ ! -f "$DSH_BIN" ]; then
  echo "[dsh] Harness CLI not found. Please run DeepSeek Harness Desktop to install it first." >&2
  exit 1
fi
exec "$NODE" "$DSH_BIN" "$@"
"#,
        app_dir = escape_path_sh(app_dir),
        dsh_bin = escape_path_sh(&dsh_bin),
        user_dsh = SH_USER_DSH_PRECEDENCE,
        dsh_home = escape_path_sh(&dsh_home),
        node_resolve = SH_NODE_RESOLVE,
    )
}

// ---------------------------------------------------------------------------
// pnpm shim（额外带"用户 pnpm 优先"逻辑，见各函数注释）
//
// `DSH_PREFER_BUNDLED_PNPM=1`（应用内部插件安装注入，见 service/plugin/install.rs）
// 时改为捆绑版优先：跳过用户 pnpm 直接运行捆绑 pnpm.cjs，仅当捆绑缺失时回退
// 用户 pnpm。默认（未设置）行为不变：用户 pnpm 优先。
// ---------------------------------------------------------------------------

/// Windows `pnpm.cmd` 内容：优先转发用户自己安装的 pnpm（`where pnpm` 遍历、
/// 跳过本 shim 目录、只收 `.cmd/.exe/.bat`），否则用 node 运行捆绑 pnpm.cjs。
/// `DSH_PREFER_BUNDLED_PNPM=1` 时捆绑版优先（见模块头注）。
///
/// 实现要点：
/// - 不用 `findstr` 匹配路径（`\` 会被当正则转义导致过滤失效）；
/// - 块内变量判断用 for 变量（`%%~xp`）而非 `%VAR%`（块解析时机陷阱）。
pub fn build_pnpm_cmd_shim(app_dir: &Path) -> String {
    let pnpm_bin = app_dir.join("dependencies/pnpm/bin/pnpm.cjs");

    format!(
        r#"@echo off
rem DeepSeek Harness Desktop - pnpm command shim (generated)
rem Do not edit: regenerated by the desktop app on install/startup.
setlocal
set "APP_DIR={app_dir}"
set "PNPM_BIN={pnpm_bin}"
rem Use bundled MinGit only when system Git lacks its HTTPS transport helper.
set "SYSTEM_GIT_WORKS="
for /f "delims=" %%g in ('git --exec-path 2^>nul') do if exist "%%g\git-remote-https.exe" set "SYSTEM_GIT_WORKS=1"
if not defined SYSTEM_GIT_WORKS if exist "%APP_DIR%\dependencies\git\cmd\git.exe" set "PATH=%APP_DIR%\dependencies\git\cmd;%PATH%"

rem App-internal installs (DSH_PREFER_BUNDLED_PNPM=1) use the bundled pnpm,
rem falling back to the user's only when the bundled one is missing.
if "%DSH_PREFER_BUNDLED_PNPM%"=="1" (
  if exist "%PNPM_BIN%" goto :after_user
)

rem Use the exact user pnpm discovered by the desktop app.
if defined DSH_PNPM (
  if exist "%DSH_PNPM%" goto :use_selected
)

rem Prefer a user-installed pnpm (skip our own shim dir), fall back to bundled.
rem Accept only executable extensions (.cmd/.exe/.bat), ignore extensionless shell scripts.
set "SELF_PREFIX=%~dp0"
set "SELF_PREFIX=%SELF_PREFIX:~0,-1%"
set "USER_PNPM="
for /f "delims=" %%p in ('where pnpm 2^>nul') do (
  if not defined USER_PNPM (
    if /i not "%%p"=="%SELF_PREFIX%\pnpm.cmd" (
      if /i not "%%p"=="%SELF_PREFIX%\pnpm.exe" (
        if /i not "%%p"=="%SELF_PREFIX%\pnpm.bat" (
          if /i "%%~xp"==".cmd" set "USER_PNPM=%%p"
          if /i "%%~xp"==".exe" set "USER_PNPM=%%p"
          if /i "%%~xp"==".bat" set "USER_PNPM=%%p"
        )
      )
    )
  )
)
if defined USER_PNPM goto :use_user

goto :after_user

:use_selected
call "%DSH_PNPM%" %*
exit /b %ERRORLEVEL%

:use_user
call "%USER_PNPM%" %*
exit /b %ERRORLEVEL%

:after_user
{node_resolve}
:launch
if not exist "%PNPM_BIN%" goto :no_pnpm
"%NODE%" "%PNPM_BIN%" %*
exit /b %ERRORLEVEL%

:no_pnpm
echo [pnpm] pnpm not found. Please run DeepSeek Harness Desktop to install it first. 1>&2
exit /b 1

:no_node
echo [pnpm] Node.js runtime not found. Please run DeepSeek Harness Desktop to install it first. 1>&2
exit /b 1
"#,
        app_dir = escape_path_cmd(app_dir),
        pnpm_bin = escape_path_cmd(&pnpm_bin),
        node_resolve = CMD_NODE_RESOLVE,
    )
}

/// Windows `pnpm.ps1` 内容：优先转发用户 pnpm（`Get-Command pnpm -All`，
/// 排除本 shim 目录），否则用 node 运行捆绑 pnpm.cjs。
/// `DSH_PREFER_BUNDLED_PNPM=1` 时捆绑版优先（见模块头注）。
pub fn build_pnpm_ps1_shim(app_dir: &Path) -> String {
    let pnpm_bin = app_dir.join("dependencies/pnpm/bin/pnpm.cjs");

    format!(
        r#"# DeepSeek Harness Desktop - pnpm command shim (generated)
# Do not edit: regenerated by the desktop app on install/startup.
$ErrorActionPreference = "Stop"
$appDir = '{app_dir}'
$pnpmBin = '{pnpm_bin}'
# Use bundled MinGit only when system Git lacks its HTTPS transport helper.
$systemGitWorks = $false
try {{
    $gitExecPath = & git --exec-path 2> $null
    $systemGitWorks = ($LASTEXITCODE -eq 0) -and (Test-Path -LiteralPath (Join-Path $gitExecPath 'git-remote-https.exe'))
}} catch {{}}
if (-not $systemGitWorks) {{
    $gitDir = Join-Path $appDir 'dependencies\git\cmd'
    if (Test-Path -LiteralPath (Join-Path $gitDir 'git.exe')) {{
        $env:PATH = $gitDir + ';' + $env:PATH
    }}
}}

$useBundled = $env:DSH_PREFER_BUNDLED_PNPM -eq '1' -and (Test-Path -LiteralPath $pnpmBin -PathType Leaf)

# Use the exact user pnpm discovered by the desktop app unless bundled was requested.
if (-not $useBundled -and $env:DSH_PNPM -and (Test-Path -LiteralPath $env:DSH_PNPM -PathType Leaf)) {{
    & $env:DSH_PNPM @args
    exit $LASTEXITCODE
}}

# Prefer a user-installed pnpm (skip our own shim dir), fall back to bundled.
if (-not $useBundled) {{
    $selfDir = $PSScriptRoot.TrimEnd('\') + '\'
    $userPnpm = Get-Command pnpm -All -ErrorAction SilentlyContinue |
        Where-Object {{ $_.Source -and -not $_.Source.StartsWith($selfDir, [System.StringComparison]::OrdinalIgnoreCase) }} |
        Select-Object -First 1
    if ($userPnpm) {{
        & $userPnpm.Source @args
        exit $LASTEXITCODE
    }}
}}

{node_resolve}

if (-not (Test-Path -LiteralPath $pnpmBin)) {{
    Write-Error '[pnpm] pnpm not found. Please run DeepSeek Harness Desktop to install it first.'
    exit 1
}}
& $node $pnpmBin @args
exit $LASTEXITCODE
"#,
        app_dir = escape_path_ps1(app_dir),
        pnpm_bin = escape_path_ps1(&pnpm_bin),
        node_resolve = PS1_NODE_RESOLVE,
    )
}

/// Unix `pnpm` shell 脚本内容（POSIX sh）：按 PATH 顺序转发第一个非本目录
/// 的用户 pnpm，否则用 node 运行捆绑 pnpm.cjs。`DSH_PREFER_BUNDLED_PNPM=1`
/// 时捆绑版优先（见模块头注）。
#[cfg_attr(all(windows, not(test)), allow(dead_code))]
pub fn build_pnpm_sh_shim(app_dir: &Path) -> String {
    let pnpm_bin = app_dir.join("dependencies/pnpm/bin/pnpm.cjs");

    format!(
        r#"#!/bin/sh
# DeepSeek Harness Desktop - pnpm command shim (generated)
# Do not edit: regenerated by the desktop app on install/startup.
APP_DIR='{app_dir}'
PNPM_BIN='{pnpm_bin}'

USE_BUNDLED=
if [ "$DSH_PREFER_BUNDLED_PNPM" = "1" ] && [ -f "$PNPM_BIN" ]; then
  USE_BUNDLED=1
fi

# Use the exact user pnpm discovered by the desktop app unless bundled was requested.
if [ -z "$USE_BUNDLED" ] && [ -n "$DSH_PNPM" ] && [ -x "$DSH_PNPM" ]; then
  exec "$DSH_PNPM" "$@"
fi

# Prefer a user-installed pnpm (skip our own shim dir), fall back to bundled.
if [ -z "$USE_BUNDLED" ]; then
  SELF_DIR=$(cd "$(dirname "$0")" && pwd)
  IFS=:
  for dir in $PATH; do
    if [ "$dir" = "$SELF_DIR" ]; then
      continue
    fi
    if [ -x "$dir/pnpm" ]; then
      exec "$dir/pnpm" "$@"
    fi
  done
  unset IFS
fi

{node_resolve}

if [ ! -f "$PNPM_BIN" ]; then
  echo "[pnpm] pnpm not found. Please run DeepSeek Harness Desktop to install it first." >&2
  exit 1
fi
exec "$NODE" "$PNPM_BIN" "$@"
"#,
        app_dir = escape_path_sh(app_dir),
        pnpm_bin = escape_path_sh(&pnpm_bin),
        node_resolve = SH_NODE_RESOLVE,
    )
}

#[cfg(test)]
mod tests {
    use super::super::test_util::{sample_app_dir, sample_dsh_home, temp_dir};
    use super::*;
    use std::path::PathBuf;

    #[cfg(windows)]
    #[test]
    fn cmd_shim_contains_baked_paths() {
        let content = build_cmd_shim(&sample_app_dir(), &sample_dsh_home());
        assert!(content.contains(r"C:\Users\test\AppData\Roaming"));
        assert!(content.contains("dependencies/dsh/node_modules/@deepseek-ai/dsh/lib/bin.js"));
        assert!(content.contains(r"C:\Users\test\.dsh"));
        assert!(!content.contains("data/dsh"));
        assert!(content.contains("%*"));
    }

    #[test]
    fn cmd_shim_escapes_percent() {
        let dir = PathBuf::from(
            r"C:\Users\100%test\AppData\Roaming\io.github.hairyf.deepseek-harness-desktop",
        );
        let content = build_cmd_shim(&dir, &sample_dsh_home());
        assert!(content.contains("100%%test"));
        assert!(!content.contains(r#"set "APP_DIR=C:\Users\100%test""#));
    }

    #[cfg(windows)]
    #[test]
    fn windows_shims_configure_bundled_git_without_shadowing_system_git() {
        let dsh_cmd = build_cmd_shim(&sample_app_dir(), &sample_dsh_home());
        let dsh_ps1 = build_ps1_shim(&sample_app_dir(), &sample_dsh_home());
        let pnpm_cmd = build_pnpm_cmd_shim(&sample_app_dir());
        let pnpm_ps1 = build_pnpm_ps1_shim(&sample_app_dir());

        for content in [&dsh_cmd, &pnpm_cmd] {
            assert!(content.contains("git --exec-path 2^>nul"));
            assert!(content.contains("git-remote-https.exe"));
            assert!(content.contains(r"dependencies\git\cmd\git.exe"));
            assert!(content.contains(r"dependencies\git\cmd;%PATH%"));
            let system_probe = content.find("git --exec-path").expect("system Git probe");
            let bundled_git = content
                .find(r"dependencies\git\cmd")
                .expect("bundled Git path");
            assert!(system_probe < bundled_git);
        }
        for content in [&dsh_ps1, &pnpm_ps1] {
            assert!(content.contains("& git --exec-path 2> $null"));
            assert!(content.contains("git-remote-https.exe"));
            assert!(content.contains(r"dependencies\git\cmd"));
            assert!(content.contains("$env:PATH = $gitDir + ';' + $env:PATH"));
        }
    }

    #[test]
    fn pnpm_cmd_shim_contains_user_precedence() {
        let content = build_pnpm_cmd_shim(&sample_app_dir());
        assert!(content.contains("pnpm command shim"));
        assert!(content.contains(r#"dependencies/pnpm/bin/pnpm.cjs"#));
        assert!(content.contains("where pnpm"));
        assert!(content.contains("SELF_PREFIX"));
        assert!(content.contains(r#"call "%USER_PNPM%" %*"#));
        assert!(content.contains(":use_bundled"));
        assert!(content.contains("%APP_DIR%\\runtime\\node.exe"));
        // 应用内部安装可经 DSH_PREFER_BUNDLED_PNPM=1 强制捆绑版（须在用户搜索前生效）
        assert!(content.contains("DSH_PREFER_BUNDLED_PNPM"));
        let env_at = content.find("DSH_PREFER_BUNDLED_PNPM").unwrap();
        let exact_at = content.find("if defined DSH_PNPM").unwrap();
        let user_at = content.find("where pnpm").unwrap();
        assert!(env_at < exact_at && exact_at < user_at);
        assert_eq!(content.matches("if defined DSH_PNPM").count(), 1);
    }

    /// issue #130：真实执行生成的 cmd shim，确保用户 pnpm 的失败码不会因 cmd
    /// 括号块预展开 `%ERRORLEVEL%` 而被吞成 0。
    #[cfg(windows)]
    #[test]
    fn pnpm_cmd_shim_propagates_user_exit_code_in_real_cmd() {
        let dir = temp_dir("pnpm-exit-code");
        let shim_dir = dir.join("desktop-bin");
        let user_dir = dir.join("user-bin");
        std::fs::create_dir_all(&shim_dir).unwrap();
        std::fs::create_dir_all(&user_dir).unwrap();
        let shim = shim_dir.join("pnpm.cmd");
        std::fs::write(&shim, build_pnpm_cmd_shim(&dir.join("app"))).unwrap();
        std::fs::write(
            user_dir.join("pnpm.cmd"),
            "@echo off\r\necho REAL_USER_PNPM\r\nexit /b 37\r\n",
        )
        .unwrap();
        let system_root = std::env::var_os("SystemRoot").unwrap_or_else(|| "C:\\Windows".into());
        let system32 = PathBuf::from(&system_root).join("System32");
        let path = std::env::join_paths([&shim_dir, &user_dir, &system32]).unwrap();
        let output = std::process::Command::new(system32.join("cmd.exe"))
            .args(["/d", "/c"])
            .arg(&shim)
            .arg("--version")
            .env("PATH", path)
            .env("SystemRoot", system_root)
            .output()
            .unwrap();
        assert_eq!(output.status.code(), Some(37));
        assert!(String::from_utf8_lossy(&output.stdout).contains("REAL_USER_PNPM"));
        let _ = std::fs::remove_dir_all(dir);
    }

    /// issue #121：选定 pnpm 即使不在子进程 PATH 中，也必须由 shim 执行。
    #[cfg(windows)]
    #[test]
    fn pnpm_cmd_shim_uses_selected_pnpm_with_restricted_path() {
        let dir = temp_dir("pnpm-selected");
        let selected = dir.join("selected pnpm.cmd");
        std::fs::write(
            &selected,
            "@echo off\r\necho SELECTED_PNPM %*\r\nexit /b 37\r\n",
        )
        .unwrap();
        let selected = dunce::canonicalize(&selected).unwrap();
        assert!(!selected.to_string_lossy().starts_with(r"\\?\"));
        let shim = dir.join("pnpm.cmd");
        std::fs::write(&shim, build_pnpm_cmd_shim(&dir.join("app"))).unwrap();
        let system_root = std::env::var_os("SystemRoot").unwrap_or_else(|| "C:\\Windows".into());
        let system32 = PathBuf::from(&system_root).join("System32");
        let output = std::process::Command::new(system32.join("cmd.exe"))
            .args(["/d", "/c"])
            .arg(&shim)
            .arg("probe-121")
            .env("PATH", &system32)
            .env("SystemRoot", system_root)
            .env("DSH_PNPM", &selected)
            .env("DSH_PREFER_BUNDLED_PNPM", "1")
            .output()
            .unwrap();
        assert_eq!(output.status.code(), Some(37));
        assert!(String::from_utf8_lossy(&output.stdout).contains("SELECTED_PNPM probe-121"));
        let _ = std::fs::remove_dir_all(dir);
    }

    /// 两个变量同时存在且捆绑文件可用时，显式的捆绑策略必须优先。
    #[cfg(windows)]
    #[test]
    fn pnpm_cmd_shim_prefers_existing_bundle_over_selected_path() {
        let dir = temp_dir("pnpm-both-vars");
        let app_dir = dir.join("app");
        let pnpm_bin = app_dir.join("dependencies/pnpm/bin/pnpm.cjs");
        std::fs::create_dir_all(pnpm_bin.parent().unwrap()).unwrap();
        std::fs::write(&pnpm_bin, "fixture").unwrap();
        let selected = dir.join("selected.cmd");
        let node = dir.join("node.cmd");
        std::fs::write(&selected, "@echo off\r\necho SELECTED\r\n").unwrap();
        std::fs::write(&node, "@echo off\r\necho BUNDLED %*\r\nexit /b 0\r\n").unwrap();
        let shim = dir.join("pnpm.cmd");
        std::fs::write(&shim, build_pnpm_cmd_shim(&app_dir)).unwrap();
        let system_root = std::env::var_os("SystemRoot").unwrap_or_else(|| "C:\\Windows".into());
        let system32 = PathBuf::from(&system_root).join("System32");
        let output = std::process::Command::new(system32.join("cmd.exe"))
            .args(["/d", "/c"])
            .arg(&shim)
            .arg("both-vars")
            .env("PATH", &system32)
            .env("SystemRoot", system_root)
            .env("DSH_NODE", &node)
            .env("DSH_PNPM", &selected)
            .env("DSH_PREFER_BUNDLED_PNPM", "1")
            .output()
            .unwrap();
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(output.status.success());
        assert!(stdout.contains("BUNDLED"));
        assert!(!stdout.contains("SELECTED"));
        let _ = std::fs::remove_dir_all(dir);
    }

    #[test]
    fn pnpm_ps1_shim_contains_user_precedence() {
        let content = build_pnpm_ps1_shim(&sample_app_dir());
        assert!(content.contains("Get-Command pnpm -All"));
        assert!(content.contains("$PSScriptRoot"));
        assert!(content.contains("$userPnpm.Source"));
        assert!(content.contains("@args"));
        assert!(content.contains("Join-Path $appDir 'runtime\\node.exe'"));
        assert!(content.contains("$env:DSH_PREFER_BUNDLED_PNPM"));
        assert!(content.contains("$env:DSH_PNPM"));
        let bundled_at = content.find("$useBundled =").unwrap();
        let exact_at = content.find("& $env:DSH_PNPM @args").unwrap();
        let path_at = content.find("Get-Command pnpm -All").unwrap();
        assert!(bundled_at < exact_at && exact_at < path_at);
    }

    #[cfg(windows)]
    #[test]
    fn pnpm_ps1_shim_dispatches_exact_path_with_spaces_args_and_exit_code() {
        let dir = temp_dir("pnpm-ps1-selected");
        let selected = dir.join("selected pnpm.cmd");
        std::fs::write(&selected, "@echo off\r\necho SELECTED:%*\r\nexit /b 37\r\n").unwrap();
        let shim = dir.join("pnpm.ps1");
        std::fs::write(&shim, build_pnpm_ps1_shim(&dir.join("app"))).unwrap();
        let system_root = std::env::var_os("SystemRoot").unwrap_or_else(|| "C:\\Windows".into());
        let powershell =
            PathBuf::from(&system_root).join("System32/WindowsPowerShell/v1.0/powershell.exe");
        let output = std::process::Command::new(powershell)
            .args(["-NoProfile", "-ExecutionPolicy", "Bypass", "-File"])
            .arg(&shim)
            .args(["alpha beta", "gamma"])
            .env("DSH_PNPM", &selected)
            .env("DSH_PREFER_BUNDLED_PNPM", "1")
            .output()
            .unwrap();
        assert_eq!(output.status.code(), Some(37));
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(
            stdout.contains("SELECTED:\"alpha beta\" gamma"),
            "unexpected stdout: {stdout:?}"
        );
        let _ = std::fs::remove_dir_all(dir);
    }

    #[cfg(windows)]
    #[test]
    fn pnpm_ps1_shim_prefers_existing_bundle_over_selected_path() {
        let dir = temp_dir("pnpm-ps1-both-vars");
        let app_dir = dir.join("app");
        let pnpm_bin = app_dir.join("dependencies/pnpm/bin/pnpm.cjs");
        std::fs::create_dir_all(pnpm_bin.parent().unwrap()).unwrap();
        std::fs::write(&pnpm_bin, "fixture").unwrap();
        let selected = dir.join("selected.cmd");
        let node = dir.join("node.cmd");
        std::fs::write(&selected, "@echo off\r\necho SELECTED\r\n").unwrap();
        std::fs::write(&node, "@echo off\r\necho BUNDLED %*\r\nexit /b 0\r\n").unwrap();
        let shim = dir.join("pnpm.ps1");
        std::fs::write(&shim, build_pnpm_ps1_shim(&app_dir)).unwrap();
        let system_root = std::env::var_os("SystemRoot").unwrap_or_else(|| "C:\\Windows".into());
        let powershell =
            PathBuf::from(&system_root).join("System32/WindowsPowerShell/v1.0/powershell.exe");
        let output = std::process::Command::new(powershell)
            .args(["-NoProfile", "-ExecutionPolicy", "Bypass", "-File"])
            .arg(&shim)
            .arg("both-vars")
            .env("DSH_NODE", &node)
            .env("DSH_PNPM", &selected)
            .env("DSH_PREFER_BUNDLED_PNPM", "1")
            .output()
            .unwrap();
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(
            output.status.success(),
            "stderr: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        assert!(stdout.contains("BUNDLED"), "unexpected stdout: {stdout:?}");
        assert!(!stdout.contains("SELECTED"));
        let _ = std::fs::remove_dir_all(dir);
    }

    #[test]
    fn pnpm_sh_shim_contains_user_precedence() {
        let content = build_pnpm_sh_shim(&sample_app_dir());
        assert!(content.starts_with("#!/bin/sh"));
        assert!(content.contains(r#"exec "$dir/pnpm" "$@""#));
        assert!(content.contains("SELF_DIR"));
        assert!(content.contains(r#"exec "$NODE" "$PNPM_BIN" "$@""#));
        assert!(content.contains(r#"$APP_DIR/runtime/bin/node"#));
        assert!(content.contains("DSH_PREFER_BUNDLED_PNPM"));
        assert!(content.contains(r#"exec "$DSH_PNPM" "$@""#));
        let bundled_at = content.find("USE_BUNDLED=").unwrap();
        let exact_at = content.find(r#"exec "$DSH_PNPM" "$@""#).unwrap();
        let path_at = content.find("for dir in $PATH").unwrap();
        assert!(bundled_at < exact_at && exact_at < path_at);
    }

    #[cfg(unix)]
    #[test]
    fn pnpm_sh_shim_dispatches_exact_path_with_spaces_args_and_exit_code() {
        use std::os::unix::fs::PermissionsExt;

        let dir = temp_dir("pnpm-sh-selected");
        let selected = dir.join("selected pnpm");
        std::fs::write(
            &selected,
            "#!/bin/sh\nprintf 'SELECTED:%s\\n' \"$*\"\nexit 37\n",
        )
        .unwrap();
        let mut permissions = std::fs::metadata(&selected).unwrap().permissions();
        permissions.set_mode(0o700);
        std::fs::set_permissions(&selected, permissions).unwrap();
        let shim = dir.join("pnpm");
        std::fs::write(&shim, build_pnpm_sh_shim(&dir.join("app"))).unwrap();
        let mut permissions = std::fs::metadata(&shim).unwrap().permissions();
        permissions.set_mode(0o700);
        std::fs::set_permissions(&shim, permissions).unwrap();

        let output = std::process::Command::new(&shim)
            .args(["alpha beta", "gamma"])
            .env("PATH", "/usr/bin:/bin")
            .env("DSH_PNPM", &selected)
            .env("DSH_PREFER_BUNDLED_PNPM", "1")
            .output()
            .unwrap();
        assert_eq!(output.status.code(), Some(37));
        assert_eq!(
            String::from_utf8_lossy(&output.stdout),
            "SELECTED:alpha beta gamma\n"
        );
        let _ = std::fs::remove_dir_all(dir);
    }

    #[cfg(unix)]
    #[test]
    fn pnpm_sh_shim_prefers_existing_bundle_over_selected_path() {
        use std::os::unix::fs::PermissionsExt;

        let dir = temp_dir("pnpm-sh-both-vars");
        let app_dir = dir.join("app");
        let pnpm_bin = app_dir.join("dependencies/pnpm/bin/pnpm.cjs");
        std::fs::create_dir_all(pnpm_bin.parent().unwrap()).unwrap();
        std::fs::write(&pnpm_bin, "fixture").unwrap();
        let selected = dir.join("selected");
        let node = dir.join("node");
        std::fs::write(&selected, "#!/bin/sh\necho SELECTED\n").unwrap();
        std::fs::write(&node, "#!/bin/sh\necho BUNDLED \"$@\"\n").unwrap();
        for path in [&selected, &node] {
            let mut permissions = std::fs::metadata(path).unwrap().permissions();
            permissions.set_mode(0o700);
            std::fs::set_permissions(path, permissions).unwrap();
        }
        let shim = dir.join("pnpm");
        std::fs::write(&shim, build_pnpm_sh_shim(&app_dir)).unwrap();
        let mut permissions = std::fs::metadata(&shim).unwrap().permissions();
        permissions.set_mode(0o700);
        std::fs::set_permissions(&shim, permissions).unwrap();

        let output = std::process::Command::new(&shim)
            .arg("both-vars")
            .env("PATH", "/usr/bin:/bin")
            .env("DSH_NODE", &node)
            .env("DSH_PNPM", &selected)
            .env("DSH_PREFER_BUNDLED_PNPM", "1")
            .output()
            .unwrap();
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(output.status.success());
        assert!(stdout.contains("BUNDLED"));
        assert!(!stdout.contains("SELECTED"));
        let _ = std::fs::remove_dir_all(dir);
    }

    /// issue #121：桌面端注入的 DSH_NODE（预检解析出的 node 路径）必须在
    /// 本地 node / 捆绑运行时解析之前被采用——shim 与应用预检保持一致。
    #[test]
    fn cmd_shim_prefers_dsh_node_before_local_node() {
        let content = build_cmd_shim(&sample_app_dir(), &sample_dsh_home());
        let dsh_node_at = content.find("DSH_NODE").unwrap();
        let where_node_at = content.find("where node").unwrap();
        // `:node_dsh` 标签行（独占一行）位于 `:node_ok` 之后、`:use_bundled`
        // 之前；`goto :node_dsh` 引用出现在 `where node` 之前，不能作为定位点。
        let node_dsh_label_at = content.find("\n:node_dsh").unwrap();
        let node_ok_at = content.find("\n:node_ok").unwrap();
        assert!(
            dsh_node_at < where_node_at,
            "DSH_NODE must be checked before the local node search"
        );
        assert!(content.contains(r#"set "NODE=%DSH_NODE%""#));
        assert!(
            node_ok_at < node_dsh_label_at,
            "the :node_dsh label must come after :node_ok"
        );
        // Windows canonical paths may carry a \\?\ verbatim prefix; the shim
        // must strip it before launching node (issue: pnpm --version fails
        // with "The system cannot find the path specified.").
        assert!(content.contains("NODE:~0,4%"));
        assert!(content.contains("NODE:~4%"));
    }

    #[test]
    fn ps1_shim_prefers_dsh_node_before_local_node() {
        let content = build_ps1_shim(&sample_app_dir(), &sample_dsh_home());
        let dsh_node_at = content.find("$env:DSH_NODE").unwrap();
        let local_at = content.find("Get-Command node").unwrap();
        assert!(
            dsh_node_at < local_at,
            "DSH_NODE must be checked before the local node search"
        );
        // Same verbatim-prefix stripping as the CMD shim.
        assert!(content.contains("StartsWith"));
        assert!(content.contains("Substring(4)"));
    }

    #[test]
    fn sh_shim_prefers_dsh_node_before_local_node() {
        #[cfg(not(windows))]
        {
            let content = build_sh_shim(&sample_app_dir(), &sample_dsh_home());
            let dsh_node_at = content.find("$DSH_NODE").unwrap();
            let local_at = content.find("command -v node").unwrap();
            assert!(
                dsh_node_at < local_at,
                "DSH_NODE must be checked before the local node search"
            );
        }
    }

    #[cfg(windows)]
    #[test]
    fn ps1_shim_escapes_quotes() {
        let dir = PathBuf::from(
            r"C:\Users\o'brien\AppData\Roaming\io.github.hairyf.deepseek-harness-desktop",
        );
        let content = build_ps1_shim(&dir, &sample_dsh_home());
        assert!(content.contains(r"o''brien"));
        // dsh_home 同样走 ps1 转义
        assert!(content.contains(r"C:\Users\test\.dsh"));
    }

    #[test]
    fn cmd_shim_prefers_user_dsh() {
        let content = build_cmd_shim(&sample_app_dir(), &sample_dsh_home());
        assert!(content.contains("USER_DSH"));
        assert!(content.contains(r#"call "%USER_DSH%" %*"#));
        assert!(content.contains("SELF_PREFIX"));
        // 用户 dsh 优先转发应出现在捆绑启动之前
        let user_at = content.find("USER_DSH").unwrap();
        let bundled_at = content.find(":use_bundled").unwrap();
        assert!(user_at < bundled_at);
    }

    #[test]
    fn ps1_shim_prefers_user_dsh() {
        let content = build_ps1_shim(&sample_app_dir(), &sample_dsh_home());
        assert!(content.contains("Get-Command dsh -All"));
        assert!(content.contains("$userDsh.Source"));
        assert!(content.contains("$PSScriptRoot"));
        // DSH_HOME 绑定只在捆绑启动分支注入（转发用户 dsh 时保留用户环境）
        let user_at = content.find("$userDsh").unwrap();
        let home_at = content.find("$env:DSH_HOME = $dshHome").unwrap();
        assert!(user_at < home_at);
    }

    #[test]
    fn sh_shim_prefers_user_dsh() {
        #[cfg(not(windows))]
        {
            let content = build_sh_shim(&sample_app_dir(), &sample_dsh_home());
            assert!(content.contains(r#"exec "$dir/dsh" "$@""#));
            assert!(content.contains("SELF_DIR"));
            // 用户 dsh 优先 > 注入 DSH_HOME
            let user_at = content.find(r#""$dir/dsh""#).unwrap();
            let home_at = content.find("export DSH_HOME").unwrap();
            assert!(user_at < home_at);
        }
    }
}
